use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &APP_HTTP_ROUTES;

pub const APP_HTTP_ROUTES: [HttpRoute; 30] = [
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/repositories",
        "github",
        "repositories.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/repositories/sync",
        "github",
        "repositories.sync",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/issues",
        "github",
        "issues.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/issues/sync",
        "github",
        "issues.sync",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/plans",
        "github",
        "plans.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/catalog/bootstrap",
        "github",
        "catalog.bootstrap",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/integration",
        "github",
        "integration.status",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/integration",
        "github",
        "integration.link",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/github/integration",
        "github",
        "integration.unlink",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/integration/oauth/begin",
        "github",
        "integration.oauth.begin",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/github/integration/oauth/callback",
        "github",
        "integration.oauth.callback",
    ),
    // Tracker routes
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/issues",
        "github",
        "tracker.issues.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/tracker/issues",
        "github",
        "tracker.issues.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/issues/:issue_id",
        "github",
        "tracker.issues.detail",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/github/tracker/issues/:issue_id",
        "github",
        "tracker.issues.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/issues/:issue_id/comments",
        "github",
        "tracker.issues.comments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/tracker/issues/:issue_id/comments",
        "github",
        "tracker.issues.comments.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/tracker/issues/:issue_id/votes",
        "github",
        "tracker.issues.votes.toggle",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/issues/:issue_id/votes/status",
        "github",
        "tracker.issues.votes.status",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/labels",
        "github",
        "tracker.labels.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/tracker/labels",
        "github",
        "tracker.labels.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/milestones",
        "github",
        "tracker.milestones.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/tracker/milestones",
        "github",
        "tracker.milestones.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/milestones/:milestone_id/issues",
        "github",
        "tracker.milestones.issues",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/roadmaps",
        "github",
        "tracker.roadmaps.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/tracker/roadmaps",
        "github",
        "tracker.roadmaps.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/tracker/roadmaps/:roadmap_id",
        "github",
        "tracker.roadmaps.detail",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/github/tracker/roadmaps/:roadmap_id",
        "github",
        "tracker.roadmaps.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/tracker/roadmaps/:roadmap_id/items",
        "github",
        "tracker.roadmaps.items.add",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/github/tracker/roadmaps/:roadmap_id/items/:item_id",
        "github",
        "tracker.roadmaps.items.remove",
    ),
];

pub fn app_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
