[package]
name = "sdkwork-api-github-standalone-gateway"
version.workspace = true
edition.workspace = true


[[bin]]
name = "sdkwork-api-github-standalone-gateway"
path = "src/main.rs"

[dependencies]
sdkwork_api_github_assembly.workspace = true
sdkwork-api-iam-assembly.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sdkwork-web-core.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork_iam_web_adapter.workspace = true


