[package]
name = "sdkwork-api-github-assembly"
edition.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-github application HTTP plane."

[lib]
name = "sdkwork_api_github_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sqlx.workspace = true
tracing.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-github-integration-service.workspace = true
sdkwork-github-integration-repository-sqlx.workspace = true
sdkwork-github-database-host.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-routes-github-app-api.workspace = true
sdkwork-routes-github-backend-api.workspace = true
