-- SDKWork github consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_github_baseline.sql
-- SDKWork github consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_github_legacy_baseline.sql
-- github integration baseline schema

CREATE TABLE IF NOT EXISTS github_repository (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    full_name TEXT NOT NULL,
    owner TEXT NOT NULL,
    description TEXT,
    default_branch TEXT,
    html_url TEXT,
    is_private INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS github_issue (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    repository_id TEXT NOT NULL,
    number INTEGER NOT NULL,
    title TEXT NOT NULL,
    state TEXT NOT NULL,
    html_url TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS github_plan (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    repository_id TEXT,
    title TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS github_plan_item (
    id TEXT PRIMARY KEY NOT NULL,
    plan_id TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    issue_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- folded migration: migrations/postgres/0002_github_provider_account.sql
-- github provider account linking for tenant-scoped integration credentials

CREATE TABLE IF NOT EXISTS github_provider_account (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    provider TEXT NOT NULL DEFAULT 'github',
    external_account_id TEXT,
    access_token_cipher TEXT NOT NULL,
    scopes TEXT,
    status TEXT NOT NULL,
    last_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (tenant_id, organization_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_github_provider_account_scope
    ON github_provider_account (tenant_id, organization_id, provider, status);

-- folded migration: migrations/postgres/0003_github_oauth_pending.sql
-- ephemeral OAuth state for GitHub integration linking

CREATE TABLE IF NOT EXISTS github_oauth_pending (
    state TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_github_oauth_pending_expires
    ON github_oauth_pending (expires_at);

-- folded migration: migrations/postgres/0004_github_referential_integrity.sql
-- Referential integrity constraints for the GitHub integration schema.

CREATE INDEX IF NOT EXISTS idx_github_issue_repository
    ON github_issue (repository_id);

CREATE INDEX IF NOT EXISTS idx_github_issue_scope
    ON github_issue (tenant_id, organization_id, repository_id);

CREATE INDEX IF NOT EXISTS idx_github_plan_repository
    ON github_plan (repository_id);

CREATE INDEX IF NOT EXISTS idx_github_plan_scope
    ON github_plan (tenant_id, organization_id, repository_id);

CREATE INDEX IF NOT EXISTS idx_github_plan_item_plan
    ON github_plan_item (plan_id);

CREATE INDEX IF NOT EXISTS idx_github_plan_item_issue
    ON github_plan_item (issue_id);

ALTER TABLE github_issue
    DROP CONSTRAINT IF EXISTS fk_github_issue_repository;

ALTER TABLE github_issue
    ADD CONSTRAINT fk_github_issue_repository
    FOREIGN KEY (repository_id) REFERENCES github_repository (id) ON DELETE CASCADE;

ALTER TABLE github_plan
    DROP CONSTRAINT IF EXISTS fk_github_plan_repository;

ALTER TABLE github_plan
    ADD CONSTRAINT fk_github_plan_repository
    FOREIGN KEY (repository_id) REFERENCES github_repository (id) ON DELETE SET NULL;

ALTER TABLE github_plan_item
    DROP CONSTRAINT IF EXISTS fk_github_plan_item_plan;

ALTER TABLE github_plan_item
    ADD CONSTRAINT fk_github_plan_item_plan
    FOREIGN KEY (plan_id) REFERENCES github_plan (id) ON DELETE CASCADE;

ALTER TABLE github_plan_item
    DROP CONSTRAINT IF EXISTS fk_github_plan_item_issue;

ALTER TABLE github_plan_item
    ADD CONSTRAINT fk_github_plan_item_issue
    FOREIGN KEY (issue_id) REFERENCES github_issue (id) ON DELETE SET NULL;

-- ════════════════════════════════════════════════════════
-- Tracker domain: user issues, labels, milestones, roadmaps
-- ════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS github_tracker_label (
    id              TEXT PRIMARY KEY NOT NULL,
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    name            TEXT NOT NULL,
    color           TEXT NOT NULL DEFAULT '6e7681',
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    UNIQUE (tenant_id, organization_id, name)
);

CREATE TABLE IF NOT EXISTS github_tracker_milestone (
    id              TEXT PRIMARY KEY NOT NULL,
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    title           TEXT NOT NULL,
    description     TEXT,
    status          TEXT NOT NULL DEFAULT 'open',
    due_date        TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS github_tracker_issue (
    id              TEXT PRIMARY KEY NOT NULL,
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    title           TEXT NOT NULL,
    description     TEXT NOT NULL,
    type            TEXT NOT NULL DEFAULT 'bug',
    status          TEXT NOT NULL DEFAULT 'open',
    priority        TEXT NOT NULL DEFAULT 'medium',
    submitted_by    TEXT NOT NULL,
    assignee_id     TEXT,
    milestone_id    TEXT,
    github_issue_id TEXT,
    vote_count      INTEGER NOT NULL DEFAULT 0,
    comment_count   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS github_tracker_issue_label (
    issue_id        TEXT NOT NULL,
    label_id        TEXT NOT NULL,
    PRIMARY KEY (issue_id, label_id)
);

CREATE TABLE IF NOT EXISTS github_tracker_comment (
    id              TEXT PRIMARY KEY NOT NULL,
    issue_id        TEXT NOT NULL,
    author_id       TEXT NOT NULL,
    content         TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS github_tracker_vote (
    id              TEXT PRIMARY KEY NOT NULL,
    issue_id        TEXT NOT NULL,
    user_id         TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    UNIQUE (issue_id, user_id)
);

CREATE TABLE IF NOT EXISTS github_tracker_roadmap (
    id              TEXT PRIMARY KEY NOT NULL,
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    title           TEXT NOT NULL,
    description     TEXT,
    status          TEXT NOT NULL DEFAULT 'active',
    start_date      TEXT,
    target_date     TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS github_tracker_roadmap_item (
    id              TEXT PRIMARY KEY NOT NULL,
    roadmap_id      TEXT NOT NULL,
    issue_id        TEXT NOT NULL,
    track           TEXT,
    start_date      TEXT,
    target_date     TEXT,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tracker_label_scope
    ON github_tracker_label (tenant_id, organization_id);

CREATE INDEX IF NOT EXISTS idx_tracker_milestone_scope
    ON github_tracker_milestone (tenant_id, organization_id, status);

CREATE INDEX IF NOT EXISTS idx_tracker_issue_scope
    ON github_tracker_issue (tenant_id, organization_id, type, status);

CREATE INDEX IF NOT EXISTS idx_tracker_issue_milestone
    ON github_tracker_issue (milestone_id);

CREATE INDEX IF NOT EXISTS idx_tracker_comment_issue
    ON github_tracker_comment (issue_id, created_at);

CREATE INDEX IF NOT EXISTS idx_tracker_vote_issue
    ON github_tracker_vote (issue_id, user_id);

CREATE INDEX IF NOT EXISTS idx_tracker_roadmap_scope
    ON github_tracker_roadmap (tenant_id, organization_id, status);

CREATE INDEX IF NOT EXISTS idx_tracker_roadmap_item_roadmap
    ON github_tracker_roadmap_item (roadmap_id, sort_order);
